export const banner_image = [
    "/images/frame1.png",
    "/images/frame2.png",
]

export const flash_sale = [
    {
        id: 1,
        title: "HAVIT HV-G92 Gamepad",
        detaile_dsc: "Experience precision and comfort with the HAVIT HV-G92 Gamepad, designed for both casual and competitive gamers. Featuring ergonomic design and responsive buttons.",
        price: 120,
        rating: 5,
        discount: "-40%",
        image: "/images/flash-sale-1.png",
    },
    {
        id: 2,
        title: "AK-900 Wired Keyboard",
        detaile_dsc: "Upgrade your typing and gaming experience with the AK-900 Wired Keyboard. Durable and responsive, it’s perfect for both work and play.",
        price: 120,
        rating: 5,
        discount: "-40%",
        image: "/images/flash-sale-2.png",
    },
    {
        id: 3,
        title: "IPS LCD Gaming Monitor",
        detaile_dsc: "Immerse yourself in vibrant visuals with the IPS LCD Gaming Monitor. Perfect for gamers and creators, it offers stunning clarity and fast refresh rates.",
        price: 120,
        rating: 5,
        discount: "-40%",
        image: "/images/flash-sale-3.png",
    },
    {
        id: 4,
        title: "S-Series Comfort Chair",
        detaile_dsc: "Stay comfortable during long gaming or work sessions with the S-Series Comfort Chair. Designed with ergonomic support and premium materials.",
        price: 120,
        rating: 5,
        discount: "-40%",
        image: "/images/flash-sale-4.png",
    },
    {
        id: 5,
        title: "GP11 Shooter USB Gamepad",
        detaile_dsc: "Take control of your games with the GP11 Shooter USB Gamepad. Featuring a sleek design, precise controls, and plug-and-play compatibility.",
        price: 120,
        rating: 5,
        discount: "-40%",
        image: "/images/flash-sale-5.png",
    },
    {
        id: 6,
        title: "Jr. Zoom Soccer Cleats",
        detaile_dsc: "Enhance your performance on the field with the Jr. Zoom Soccer Cleats. Lightweight, durable, and designed for maximum grip and speed.",
        price: 120,
        rating: 5,
        discount: "-40%",
        image: "/images/flash-sale-6.png",
    },
];


export const best_selling_products = [
    {
        id: 1,
        title: "The North Coat",
        detaile_dsc: "Stay warm and stylish with The North Coat. Designed for ultimate comfort and protection against harsh weather, it's perfect for any adventure.",
        price: 120,
        rating: 5,
        discount: "-40%",
        image: "/images/best-selling-products-1.png",
    },
    {
        id: 2,
        title: "Gucci Duffle Bag",
        detaile_dsc: "Travel in style with the Gucci Duffle Bag. Made with premium materials, it offers ample space for your essentials and a luxurious design.",
        price: 120,
        rating: 5,
        discount: "-40%",
        image: "/images/best-selling-products-2.png",
    },
    {
        id: 3,
        title: "RGB Liquid CPU Cooler",
        detaile_dsc: "Keep your system cool and performing at its best with the RGB Liquid CPU Cooler. It features stunning RGB lighting and efficient thermal management.",
        price: 120,
        rating: 5,
        discount: "-40%",
        image: "/images/best-selling-products-3.png",
    },
    {
        id: 4,
        title: "Small Bookshelf",
        detaile_dsc: "Organize your books and decor with the Small Bookshelf. Compact yet spacious, it's perfect for enhancing your home or office space.",
        price: 120,
        rating: 5,
        discount: "-40%",
        image: "/images/best-selling-products-4.png",
    },
];



export const explore_our_products = [
    {
        id: 1,
        title: "Breed Dry Dog Food",
        detaile_dsc: "Experience precision and comfort with the HAVIT HV-G92 Gamepad, designed for both casual and competitive gamers. Featuring ergonomic design and responsive buttons.",
        price: 120,
        rating: 5,
        discount: "-40%",
        image: "/images/explore_our_product-1.png",
    },
    {
        id: 2,
        title: "CANON EOS DSLR Camera",
        detaile_dsc: "Upgrade your typing and gaming experience with the AK-900 Wired Keyboard. Durable and responsive, it’s perfect for both work and play.",
        price: 120,
        rating: 5,
        discount: "-40%",
        image: "/images/explore_our_product-2.png",
    },
    {
        id: 3,
        title: "ASUS FHD Gaming Laptop",
        detaile_dsc: "Immerse yourself in vibrant visuals with the IPS LCD Gaming Monitor. Perfect for gamers and creators, it offers stunning clarity and fast refresh rates.",
        price: 120,
        rating: 5,
        discount: "-40%",
        image: "/images/explore_our_product-3.png",
    },
    {
        id: 4,
        title: "Curology Product Set ",
        detaile_dsc: "Stay comfortable during long gaming or work sessions with the S-Series Comfort Chair. Designed with ergonomic support and premium materials.",
        price: 120,
        rating: 5,
        discount: "-40%",
        image: "/images/explore_our_product-4.png",
    },
    {
        id: 5,
        title: "Kids Electric Car",
        detaile_dsc: "Stay comfortable during long gaming or work sessions with the S-Series Comfort Chair. Designed with ergonomic support and premium materials.",
        price: 120,
        rating: 5,
        discount: "-40%",
        image: "/images/explore_our_product-5.png",
    },
    {
        id: 6,
        title: "Jr. Zoom Soccer Cleats",
        detaile_dsc: "Stay comfortable during long gaming or work sessions with the S-Series Comfort Chair. Designed with ergonomic support and premium materials.",
        price: 120,
        rating: 5,
        discount: "-40%",
        image: "/images/explore_our_product-6.png",
    },
    {
        id: 7,
        title: "GP11 Shooter USB Gamepad",
        detaile_dsc: "Stay comfortable during long gaming or work sessions with the S-Series Comfort Chair. Designed with ergonomic support and premium materials.",
        price: 120,
        rating: 5,
        discount: "-40%",
        image: "/images/explore_our_product-7.png",
    },
    {
        id: 8,
        title: "Quilted Satin Jacket",
        detaile_dsc: "Stay comfortable during long gaming or work sessions with the S-Series Comfort Chair. Designed with ergonomic support and premium materials.",
        price: 120,
        rating: 5,
        discount: "-40%",
        image: "/images/explore_our_product-8.png",
    },
    {
        id: 9,
        title: "Small BookSelf",
        detaile_dsc: "Stay comfortable during long gaming or work sessions with the S-Series Comfort Chair. Designed with ergonomic support and premium materials.",
        price: 120,
        rating: 5,
        discount: "-40%",
        image: "/images/best-selling-products-4.png",
    },
    {
        id: 10,
        title: "Gucci duffle bag",
        detaile_dsc: "Travel in style with the Gucci Duffle Bag. Made with premium materials, it offers ample space for your essentials and a luxurious design.",
        price: 120,
        rating: 5,
        discount: "-40%",
        image: "/images/best-selling-products-2.png",
    },
    {
        id: 11,
        title: "IPS LCD Gaming Monitor",
        detaile_dsc: "Immerse yourself in vibrant visuals with the IPS LCD Gaming Monitor. Perfect for gamers and creators, it offers stunning clarity and fast refresh rates.",
        price: 120,
        rating: 5,
        discount: "-40%",
        image: "/images/flash-sale-3.png",
    },
    {
        id: 12,
        title: "AK-900 Wired Keyboard",
        detaile_dsc: "Upgrade your typing and gaming experience with the AK-900 Wired Keyboard. Durable and responsive, it’s perfect for both work and play.",
        price: 120,
        rating: 5,
        discount: "-40%",
        image: "/images/flash-sale-2.png",
    },
    
];